name: Daily Leaderboard Scraper

on:
  schedule:
    - cron: "*/5 * * * *"  #'/5 0 * * *' # Runs daily at midnight UTC    

jobs:
  scrape_leaderboard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Use the required Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver_manager
          
      - name: List files
        run: |
          cd ID2223-Final-Project/my_scrapper/
          ls

      - name: Run leaderboard scraper
        run: |
          python my_scrapper/Leaderboard_scrapper.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ID2223-Final-Project/my_scrapper/leaderboard_data.csv
          git commit -m "Daily leaderboard scrape" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
